application: stage-5-project-udacity
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /.*
  script: main.app



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
